Fix test_menu_construct_from_none test case
When `menu(None)` is called, this exception happens:

  File "/tmp/pystray-0.19.4/lib/pystray/_base.py", line 661, in cleaned
    if not i.visible:
  AttributeError: 'NoneType' object has no attribute 'visible'

Adding an `not i or` before that condition will make sure that `None`
will be considered as not visible.

The test itself fails as well:

  File "/tmp/pystray-0.19.4/tests/menu_descriptor_tests.py", line 85, in test_menu_construct_from_none
    self.assertEqual(
  AssertionError: '' != '\n'

Instead just compare if `str(menu(None))` is the empty string.